;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        counsel-M-x
        dired-efap
        end-of-visual-line
        forward-to-word
        indent-for-tab-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
