;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        aj/force-save
        beginning-of-visual-line
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        counsel-M-x
        dired-do-rename
        dired-efap
        dired-flag-file-deletion
        dired-mark
        end-of-visual-line
        forward-to-word
        ibuffer-mark-for-delete
        ibuffer-mark-forward
        indent-and-open-newline
        indent-for-tab-command
        ivy-occur-delete-candidate
        kill-region
        kill-visual-line
        org-delete-char
        org-self-insert-command
        smart-rigid-unindent
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-splice-sexp
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        next-frame-in-window
        smartscan-symbol-go-forward
        sp-backward-slurp-sexp
        sp-wrap-cancel
        swiper-mc
        undefined
        ))
